
name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Run docker 
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
      
    - name: Download a file
      run: wget https://github.com/exadel-inc/CompreFace/releases/download/v1.1.0/CompreFace_1.1.0.zip
      
    - name: Unzip CompreFace  
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq CompreFace_1.1.0.zip -d compreface 
        
    - name: Show contents
      working-directory: ./compreface
      run: pwd
        
    - name: Run CompreFace
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
