name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
      
    - name: Show contents
      run: pwd
      
    - name: Build the Docker image
      run: docker build . --file Exadel.Compreface.AcceptenceTests/Dockerfile
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
